In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [2]:
from scipy import linalg

In [3]:
linalg.det(A)

2.999999999999997

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [7]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [8]:
EW, EV = linalg.eig(A)

In [9]:
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [10]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

In [11]:
v = np.array([[2],[3],[5]])

In [12]:
v

array([[2],
       [3],
       [5]])

In [13]:
v.shape

(3, 1)

In [14]:
s = linalg.solve(A,v)   # A * S = V

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

In [16]:
from scipy import sparse

In [17]:
A = sparse.lil_matrix((1000,1000))

In [18]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [21]:
A[0,:100] = np.random.rand(100)

In [22]:
A[1,100:200] = A[0,:100]

In [23]:
A.setdiag(np.random.rand(1000))

In [24]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in List of Lists format>

In [25]:
from scipy.sparse import linalg

In [26]:
# Convert this matrix to Compressed Sparse format
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [28]:
A = A.tocsr()

In [32]:
b = np.random.rand(1000)

In [30]:
linalg.spsolve(A,b)

array([ 4.00931471e+03, -3.81814408e+03,  8.93453106e-01,  2.41080021e-01,
        3.02307210e-02,  1.03869219e+00,  1.87545041e+00,  8.16012074e-01,
        1.06630351e+00,  1.00204431e+00,  9.67024446e-01,  8.98290597e-01,
        7.30514609e-01,  4.12703190e-01,  6.14037512e+01,  3.54857571e+00,
        4.65591425e-02,  8.35766978e-01,  5.68202098e-01,  6.19402864e-01,
        9.35772610e+00,  1.20187755e+00,  1.49640701e-01,  1.67153778e-01,
        3.91242671e+01,  5.81504528e+00,  3.70493513e-01,  1.25232949e-01,
        4.07300596e+01,  6.39132981e-01,  2.79803492e+00,  5.97810156e-01,
        2.07351243e+01,  7.78860989e-01,  8.19487960e-01,  1.27385810e+00,
        3.27355076e+00,  8.13536436e+00,  1.10518044e+00,  4.28077912e+00,
        7.63581289e-01,  1.36710799e-01,  1.10384153e+01,  1.59671143e+00,
        5.95426349e-01,  3.61359873e-02,  6.11721285e-01,  2.45004533e+00,
        5.25872897e-02,  1.46892822e-01,  2.68174648e+00,  6.02436994e-01,
        1.47569724e+00,  